export const SET_BANNER_LIGHTBOX_OPEN = "SET_BANNER_LIGHTBOX_OPEN"
export const SET_BANNER_LIGHTBOX_CLOSE = "SET_BANNER_LIGHTBOX_CLOSE"


export const SET_PROFILE_LIGHTBOX_OPEN = "SET_PROFILE_LIGHTBOX_OPEN"
export const SET_PROFILE_LIGHTBOX_CLOSE = "SET_PROFILE_LIGHTBOX_CLOSE"
