export const SET_BANNER = "SET_BANNER"
export const SET_PROFILE_IMAGE = "SET_PROFILE_IMAGE"
export const SET_C_PROFILE = "SET_C_PROFILE"
export const SET_IS_OWNER_OF_PROFILE = "SET_IS_OWNER_OF_PROFILE"

//MODAL
export const CLOSE_BANNER_CROP_MODAL = "CLOSE_BANNER_CROP_MODAL"
export const OPEN_BANNER_CROP_MODAL = "OPEN_BANNER_CROP_MODAL"

export const CLOSE_PROFILE_CROP_MODAL = "CLOSE_PROFILE_CROP_MODAL"
export const OPEN_PROFILE_CROP_MODAL = "OPEN_PROFILE_CROP_MODAL"

export const CLOSE_PROFILE_INFO_MODAL = "CLOSE_PROFILE_INFO_MODAL"
export const OPEN_PROFILE_INFO_MODAL = "OPEN_PROFILE_INFO_MODAL"

export const CLOSE_GALLERY_BLOCK_UPLOAD_MODAL = "CLOSE_GALLERY_BLOCK_UPLOAD_MODAL"
export const OPEN_GALLERY_BLOCK_UPLOAD_MODAL = "OPEN_GALLERY_BLOCK_UPLOAD_MODAL"

export const CLOSE_GALLERY_EDIT_MODAL = "CLOSE_GALLERY_EDIT_MODAL"
export const OPEN_GALLERY_EDIT_MODAL = "OPEN_GALLERY_EDIT_MODAL"

//Gallery
export const SET_GALLERY_SORTABLE_TRUE = "SET_GALLERY_SORTABLE_TRUE"
export const SET_GALLERY_SORTABLE_FALSE = "SET_GALLERY_SORTABLE_FALSE"