export const SET_BANNER = "SET_BANNER"
export const SET_PROFILE_IMAGE = "SET_PROFILE_IMAGE"
export const SET_C_USER = "SET_C_USER"

//MODAL
export const CLOSE_BANNER_CROP_MODAL = "CLOSE_BANNER_CROP_MODAL"
export const OPEN_BANNER_CROP_MODAL = "OPEN_BANNER_CROP_MODAL"

export const CLOSE_PROFILE_CROP_MODAL = "CLOSE_PROFILE_CROP_MODAL"
export const OPEN_PROFILE_CROP_MODAL = "OPEN_PROFILE_CROP_MODAL"
